# Generated by Django 2.2 on 2020-07-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('no_surat', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('nama_surat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('no_ayat', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hapalan.Surat')),
            ],
        ),
    ]
