# Generated by Django 2.2 on 2020-07-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapalan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='no_surat',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
